version: "3"
services:
  # APP*****************************************
  push-service:
    container_name: push-service
    build: .
    networks:
      - postgres
      - metrics
    volumes:
      - ./log:/var/log
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - spring_profiles_active=${PROFILE}
      - spring_datasource_username=${DB_USERNAME}
      - spring_datasource_password=${DB_PASSWORD}
      - telegram_hook_secret=${TG_HOOK_SECRET}
      - telegram_token=${TG_TOKEN}
      - api_key=${API_KEY}
    restart: unless-stopped

networks:
  postgres:
    external:
      name: common
  metrics:
    external:
      name: metrics