version: "3"
services:
  # APP*****************************************
  push-service:
    container_name: push-service
    build: .
    networks:
      - postgres
      - metrics
    volumes:
      - ./log:/var/log
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - PROFILE=${PROFILE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TG_HOOK_SECRET=${TG_HOOK_SECRET}
      - TG_TOKEN=${TG_TOKEN}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - api_key=${API_KEY}
    restart: unless-stopped

networks:
  postgres:
    external:
      name: common
  metrics:
    external:
      name: metrics