version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - metrics
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: unless-stopped

networks:
  metrics:
    external:
      name: metrics

volumes:
  prometheus_data: {}
