spring:
  datasource:
    url: jdbc:tc:postgresql:12.15:///${DB_NAME}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: true

telegram:
  drop-pending-updates: false
  hook:
    secret: test-secret
