spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/push-service
  jpa:
    show-sql: false

telegram:
  hook: https://push.all-easy.ru/v1/api/telegram/${telegram.hook.secret}/
  drop-pending-updates: false

spring.redis:
  host: redis
  port: 6379
  password: ${REDIS_PASSWORD}
